using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Temac.Environ;
using Temac.Tokenization;

// © Copyright 2022-2025 Magnus Levein.
// This file is part of Temac, Text Manuscript Compiler.
//
// Temac is free software: you can redistribute it and/or modify it under the
// terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// Temac is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public License along
// with Temac. If not, see <https://www.gnu.org/licenses/>.

namespace Temac.Errors;

/// <summary>
/// All exceptions generated by us shall be derived from TemacException
/// </summary>
public class TemacException : Exception
{
	public TemacException(string message) : base(message) {	}
}

public class TemacArgumentException : TemacException
{
	public Location? Location { get; private set; }

	public TemacArgumentException(Location? location, string message) : base(message)
	{
		Location = location;
	}
}

public class TemacVariableException : TemacException
{
	public int RelativePosition { get; private set; }

	public TemacVariableException(string message, int relativePosition = 0) : base(message)
	{
		RelativePosition = relativePosition;
	}
}

public class TemacTraceException : TemacException
{
	public Scope? TopScope { get; set; } = null;

	public TemacTraceException() : base("Error trace.")
	{
	}
}
